### ISSUE TITLE
Use FLASK_APP syntax for app config variable

### ISSUE THREAD

**Issue by clar-cmp** [logandk/serverless-wsgi#110]
Right now, the config syntax uses the format `path/to/some.module.app`, which tells serverless-wsgi to:

1. Set `path/to` as the `PYTHONPATH`.
2. Import `some.module` from this path.
3. Get the `app` variable from this module.

Instead, `FLASK_APP` uses `path/to/some.module` to represent the above, searching for an `app` value or a `create_app` function to call. Alternatively, you can do `path/to/some.module:app` or `path/to/some.module:create_app(list, of, arguments)` to choose a different variable or function name.

I think that using this syntax would make things a lot more flexible, allowing passing of arguments based upon stage, etc. in an easier way.

**Comment by logandk** [comment]
Thanks for the suggestion. Since `serverless-wsgi` is not a Flask-specific library, but targets multiple WSGI-enabled frameworks, I'm hesitant to adopt the Flask convention in this case. If you look at the implementation (https://github.com/pallets/flask/blob/master/src/flask/cli.py#L52), it's very specific to Flask, and will not have any use to other WSGI-enabled frameworks.

Functionally, I don't see any use cases that you could only accomplish with the current implementation, but the Flask-specific implementation would allow. If you have a specific case that proves otherwise, please let me know.

I'm going to close this issue for the time being, but please reopen if you disagree with my comments.
