### ISSUE TITLE
werkzeug is required

### ISSUE THREAD

**Issue by gmeans** [logandk/serverless-wsgi#13]
I'm trying to use this on a Django project which doesn't use `werkzeug`. In order for it to work, `werkzeug` is a required dependency. Without installing werkzeug I received:

```
Unable to import module 'wsgi': No module named werkzeug.datastructures
```

**Comment by logandk** [comment]
Indeed, and `werkzeug` should always be included in the deployment zip package, as per https://github.com/logandk/serverless-wsgi/blob/master/requirements.txt.

Are you getting this error after deploying to Lambda or when invoking `sls wsgi serve`?

**Comment by gmeans** [comment]
My use case might be an outlier. I was trying out `serverless-python-requirements` w/ the docker option because i have c-compiled extensions (psycopg2) that I want to deploy as well. I disabled this project's pack requirements option.

So since i didn't have werkzeug in my project requirements, it was never packaged.

**Comment by logandk** [comment]
Ok, that makes sense. Compiled extensions is a problem with this plugin, one option would be to skip requirement packaging entirely and leave that to `serverless-python-requirements` which has a nice solution using Docker. I do like the idea of being able to include a single plugin for a simple flask app with no extensions, though. I will close this issue and continue to consider whether to drop requirement packaging, or at least provide some additional notes in the README. Thanks for reporting.

**Comment by brettdh** [comment]
I have the same case. I've disabled `serverless-wsgi`'s requirements packaging and `serverless-python-requirements` is doing its job just fine (I checked the `.requirements` folder), but as above, I'm using Django, so I don't need `werkzeug`.

@logandk maybe I misread your response - I thought you were saying that it should work if I disable `serverless-wsgi`'s requirements packaging? But it looks like `wsgi.py` imports `werkzeug` unconditionally.

I guess then the workaround is to install `werkzeug` even though I'm not using it directly?

**Comment by logandk** [comment]
@brettdh Maybe that wasn't clear, you may disable the requirements packaging, but you will then need to add the `werkzeug` requirement yourself.

The WSGI wrapper that's included in this plugin relies on `werkzeug` for a number of things (handling headers, encodings etc.) - considering that `werkzeug` is a fairly lightweight dependency, I think it's the best option for `serverless-wsgi` rather than reimplementing those utilities inside the plugin. But I'm open to discussion on alternative approaches.

For now, I would recommend adding `werkzeug` for the single purpose of APIGW/WSGI mapping.

**Comment by andrewhaller** [comment]
This is still an issue.
