### ISSUE TITLE
Support for lambda integration type in addition to lambda-proxy?

### ISSUE THREAD

**Issue by jvarho** [logandk/serverless-wsgi#137]
Hi, the readme clearly states that only lambda-proxy integration is supported. However, async execution seems to require using the lambda integration type. Would extending to support that be within scope of this project? I could look into implementing at least basic support if so.

It would be a somewhat limited subset of the functionality, probably. For my needs responses don't even make sense, although in general they do...

**Comment by logandk** [comment]
I'm not really sure about how **WSGI** fits into async execution? Could you explain your use case?

A couple of alternatives to consider:

- Since you are not going to respond to the HTTP request, maybe you don't even need WSGI. You could just have a plain Python handler and have it process the raw Lambda event.
- Transform your event into something that resembles the event structure for `lambda-proxy` and pass it to the WSGI handler yourself.

**Comment by jvarho** [comment]
The use case is that a couple of end points in a set of backend apis ran into lambda's timeout limits, so they had to be made async. There is still a response of sorts even with async apis, the difference is that it is handled by api gateway (ok/retry/dlq) and the client always sees an immediate 202 response.

I am currently parsing the raw event in application code, but the annoying thing is that it requires making it a separate lambda function due to the different handler function. So split logs, monitoring, etc. It also bypasses the normal routing and parameter logic, making for very different logic than normal apis.

Transforming and calling the WSGI handler would still allow using all the normal routing/parsing functionality, though. Actually, yes, I could add a shim that handles all requests, transforming them based on the integration type before passing it on to wsgi_handler.handler. So, yeah, that's the way I'll go if you don't think that would be a useful fit inside serverless-wsgi.

Thanks

**Comment by logandk** [comment]
Thanks for the explanation. The main obstacle that I see is that the Lambda integration is not bound to follow any conventions in the event schema. So you'd essentially have to write VTL that transforms the event into something that's equivalent to the Lambda proxy integration and then no changes would be needed in `serverless-wsgi` anyway. You'd just have to use the right VTL in order to make it work, and we could add that to the `README`.

Or do you see any specific changes that you would need in `serverless-wsgi` to make it work?

**Comment by jvarho** [comment]
Hmm... I wasn't going to do anything so fancy. Just define the parameters in serverless.yml, e.g.

```      - http:
          path: /async/{bar}
          method: any
          async: true
          request:
            querystrings:
              foo: true
            paths:
              bar: true
```

(application/json gets automatic passthrough for the body) and then handle the incoming event format in code: https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#example-lambda-event-before-customization

**Comment by logandk** [comment]
Right, I wasn't aware that the `LAMBDA` event was so complete before any VTL transformations. It's been a while since I used it last.

I think it makes sense to support this. Ideally, we could identify whether the incoming request is a `LAMBDA` or `LAMBDA-PROXY` event and handle it accordingly. Not sure if it's feasible, but I would prefer it to be as automatic as possible rather than requiring additional configuration.
