### ISSUE TITLE
Automatically extract routes into config

### ISSUE THREAD

**Issue by tuukkamustonen** [logandk/serverless-wsgi#2]
Add command to automatically determine routes from (Flask) app and update `serverless.yml`.

Or... is there difference between the two?

**Comment by logandk** [comment]
I agree that it would be nice not having to declare the routes in several places. Since there's not a WSGI standard way of extracting known routes, this would require specialized implementations for Flask, Django, Pyramid etc. I'd prefer to stick to pure WSGI, but I realize that the majority of users will probably be deploying Flask anyway, so it may make sense to do this for Flask at least.

Another option is to use the `{proxy+}` catch-all syntax that AWS recently introduced: https://aws.amazon.com/blogs/aws/api-gateway-update-new-features-simplify-api-development/

Essentially, you should be able to declare a single HTTP event in serverless, something like:

```
functions:
  api:
    handler: wsgi.handler
    events:
      - http: ANY {proxy+}
```

I haven't tested this yet, perhaps you could try to work it out and report back?

**Comment by tuukkamustonen** [comment]
`{proxy+}` sounds cool indeed, but would cause also route all to-be-`404`s to the application?

Maybe not big of a deal, at least in hobbyist deployments. Corporations might like to use explicit mapping though (for security, cost savings, etc.).

But in the end, I guess `{proxy+}` would satisfy 99% of the cases? Probably the way to go.

Sorry, can't test it, I'm yet only evaluating different options :)

**Comment by logandk** [comment]
Yes, unknown routes would hit the application and let that return 404 rather than letting API Gateway handle it (although it actually returns 403 in that case).

`{proxy+}` is the approach that Zappa uses, so it probably suits most use cases. I will currently label this issue as a feature request and consider if we should implement something specific for Flask.

**Comment by logandk** [comment]
I've decided that this is currently outside the scope of this package, mainly since this is not something that can be implemented purely using WSGI and would require a specialized implementation for each supported library/framework. Also, for most use cases, `{proxy+}` will suffice. I'm closing the issue but will listen to anyone that disagrees with this decision.
