### ISSUE TITLE
Please rename wsgi.py

### ISSUE THREAD

**Issue by GreenSmile** [logandk/serverless-wsgi#84]
Name `wsgi` interferes with library imported in aws lambda bootstrapper and makes it difficult to use serverless-wsgi with monitoring tools like iopipe or epsagon.

Both these tools requre wrapper to be added arround AWS Lambda handler.

For example epsagon creates wrapper like (Note: this code is auto-generated by serverless-epsagon-plugin):
```
import epsagon
from wsgi import handler as handler_internal

handler = epsagon.lambda_wrapper(handler_internal)
```
As you can see it tries to import `handler` from `wsgi.py`. 

However, at this point awslambda.bootstrap.py already imported library `wsgi` (line 26):
https://gist.github.com/lucasrcosta/f884a43c59e26199591ec4e234d069f5

So epsagon handler fails to import proper `wsgi` file and raises import error.

Same issue also affects iopipe, they even have related paragraph in their README (see last part of Serverless section):
https://github.com/iopipe/iopipe-python#framework-integration

In order to use these monitoring tools with serverless-wsgi we have to create extra wrapper like it is described in iopipe docs and import wsgi.py file using `imp.load_source()` that is rather inconvenient.

I believe you can make it much easier to use if you rename `wsgi.py` not to interfere with library used in aws bootstrapper, for example `swsgi.py`.

**Comment by logandk** [comment]
@GreenSmile Thanks for investigating, I had noticed from a few earlier issues that there was a potential naming conflict. I agree that it should be renamed - in `serverless-rack`, it's called `rack_handler`. I'll follow the same convention here and call it `wsgi_handler`. Since this will be a breaking change for existing `serverless.yml` configurations, I'll try to add some logic that emits a warning and makes a temporary change in the configuration when using the current `wsgi` module as handler.
